### ISSUE TITLE
Error on constrain

### ISSUE THREAD

**Issue by helenezspeer** [bensladden/vue-displace#1] opened 2020-01-21 23:56 UTC
When I use the directive with `constrain: true`, I get an error. I'm hoping you can tell me what I'm doing wrong. Thank you!

The use: 
```
<div
	v-displace="{constrain: true}"
>
```

The errors: 
index.js?4360:524 [Vue warn]: Error in directive displace bind hook: "TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

index.js?4360:524 TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at n (vue-displace.common.js?8cf4:98)
    at e.s (vue-displace.common.js?8cf4:98)
    at new e (vue-displace.common.js?8cf4:98)
    at t.default (vue-displace.common.js?8cf4:98)
    at bind (vue-displace.common.js?8cf4:1762)
    at callHook$1 (vue.runtime.esm.js?2b0e:6680)
    at _update (vue.runtime.esm.js?2b0e:6601)
    at Array.updateDirectives (vue.runtime.esm.js?2b0e:6582)
    at invokeCreateHooks (vue.runtime.esm.js?2b0e:6069)
    at createElm (vue.runtime.esm.js?2b0e:5956)

**Comment by bensladden** [comment] 2020-01-22 03:27
Hi @helenezspeer 
This hows now been fixed in the newest version: 
[https://codesandbox.io/s/vue-displace-myxdb](https://codesandbox.io/s/vue-displace-myxdb)
Thankyou for pointing it out.

**Comment by helenezspeer** [comment] 2020-01-22 15:51
Thank you! I am able to get it to work now, but only with the default parent container. The "relativeTo" and "handle" options are not working for me. From my vue devtools, it looks like my options aren't making it to the directive.

Here is my version of your sandbox: https://codesandbox.io/s/vue-displace-rnvnl

![image](https://user-images.githubusercontent.com/5831237/72909473-16827280-3d05-11ea-956f-31dc8b3db390.png)

**Comment by bensladden** [comment] 2020-01-22 23:50
This is caused by a few reasons: when elements get inserted into the dom and when $refs update.

I have updated your example with a working version:
[https://codesandbox.io/s/vue-displace-xkk2s](https://codesandbox.io/s/vue-displace-xkk2s)

**Comment by bensladden** [comment] 2020-01-23 00:30
Note this release has introduced a bug to do with mid dragging im going to look into this

**Comment by bensladden** [comment] 2020-01-23 02:10
This has now been fixed aswell

**Comment by helenezspeer** [comment] 2020-01-23 16:57
I see that your fixes work in the demo. I still am not able to get it to work in my app, and it's not an issue with your directive -- even if I instantiate displacejs with a click even after I've loaded everything, I get "Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'" errors. Perhaps displace is not the solution for me. Thank you for your work on this.

**Comment by bensladden** [comment] 2020-01-24 10:33
Sorry to hear your issues. Perhaps its worth posting you issue on the displacejs page to get some clarification.

**Closed** 2020-01-28 02:47 UTC
Labels: awaiting Reply, bug
